=== EciStg/order-placement/other-schema/src/vnd.eci.stg.reference.1.5.0.json
{
  "id": "./vnd.eci.stg.code.1.5.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "reference",
  "description": "",
  "type": "object",
  "additionalProperties": false,

  "properties": {

    "code": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "name": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "description": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },

    "remarks": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },

    "type": { "$ref": "#/definitions/referenceTypeEnum" },

    "referencesCount": {
      "description": "number of things in the references collection",
      "type": "number",
      "minimum": 1,
      "maximum": 1000
    },

    "references": {
      "description": "",
      "type": "array",
      "minItems": 1,
      "maxItems": 1000,
      "uniqueItems": true,
      "items": {
        "$ref": "#"
      }
    }
  },

  "definitions": {
    "referenceTypeEnum": {
      "type": "string",
      "enum": ["buyer", "consumer", "manufacturer", "seller" ]
    }
  }
}

=== EciStg/order-placement/other-schema/tst/vnd.eci.stg.reference.1.5.0.json
{ "name": "wireless keyboard",
  "description": "four channel bluetooth Apple layout full size aluminum keyboard with backlit keys",
  "remarks": "requires two AAA batteries",
  "referencesCount": 2,
  "references": [{ "code": "wbkbd2345", "type": "buyer" },
                 { "code": "kbdbt4cha", "type": "seller" }]}
