=== EciStg/order-placement/rsrc-schema/src/vnd.eci.stg.receipt.1.5.0.json
{
  "id": "./vnd.eci.stg.receipt.1.5.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "receipt",
  "description": "",
  "type": "object",
  "additionalProperties": false,
  "properties": {

    "reference": { "$ref": "#/definitions/reference" },

    "code": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "name": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "description": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },

    "remarks": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },

    "when": {
      "description": "",
      "type": "string",
      "format": "date-time"
    },

    "whenExpected": {
      "description": "",
      "type": "string",
      "format": "date-time"
    },

    "billTo": { "$ref": "#/definitions/billTo" },

    "buyer": { "$ref": "#/definitions/buyer" },

    "consumer": { "$ref": "#/definitions/consumer" },

    "seller": { "$ref": "#/definitions/seller" },

    "shipTo": { "$ref": "#/definitions/shipTo" },

    "shippingMethod": { "$ref": "#/definitions/shippingMethod" },

    "location": { "$ref": "#/definitions/address" },

    "make": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "model": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "serialNumber": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "quantity": {
      "description": "",
      "type": "number",
      "minimum": 0,
      "maximum": 999999999.999999
    },

    "unitMeasure": { "$ref": "#/definitions/unitMeasure" },

    "unitCost": {
      "description": "",
      "type": "number",
      "minimum": 0,
      "maximum": 999999999999.999999
    },

    "total": { "$ref": "#/definitions/total"},

    "currency": { "$ref": "#/definitions/currency"},

    "package": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "shipment": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "tracking": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "itemsCount": {
      "description": "number of things in the items collection",
      "type": "number",
      "minimum": 1,
      "maximum": 1000
    },

    "items": {
      "description": "",
      "type": "array",
      "minItems": 1,
      "maxItems": 1000,
      "items": {
        "$ref": "#"
      }
    }
  },

  "definitions": {

    "address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "msc": {
          "description": "mail stop code",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "mtn": {
          "description": "attention line",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "rcp": {
          "description": "recipient or business name",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "alt": {
          "description": "alternate location",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "dal": {
          "description": "delivery address line",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "city": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "region": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "postalCode": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "country": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        }
      }
    },

    "billTo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "buyer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "consumer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" },

        "contract": { "$ref": "#/definitions/reference" }
      }
    },

    "contact": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        }
      }
    },

    "currency": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "number": {
          "description": "",
          "type": "number",
          "minimum": 1,
          "maximum": 999
        },

        "precision": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 18
        },

        "scale": {
          "description": "",
          "type": "number",
          "minimum": 1,
          "maximum": 6
        }
      }
    },

    "reference": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "type": { "$ref": "#/definitions/reference/definitions/referenceTypeEnum" },

        "referencesCount": {
          "description": "number of things in the references collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "references": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/reference"
          }
        }
      },

      "definitions": {
        "referenceTypeEnum": {
          "type": "string",
          "enum": ["buyer", "consumer", "manufacturer", "seller" ]
        }
      }
    },

    "seller": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "shippingMethod": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "billTo": { "$ref": "#/definitions/billTo" },

        "itemsCount": {
          "description": "number of shipping methods in the collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "items": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "items": {
            "$ref": "#/definitions/shippingMethod"
          }
        }
      }
    },

    "shipTo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" },

        "isDropShip": {
          "description": "",
          "type": "boolean"
        }
      }
    },

    "tax": {
      "type": "object",
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "amount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "authority": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "itemsCount": {
          "description": "number of things in the items collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "items": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/tax"
          }
        }
      },

      "additionalProperties": false
    },

    "total": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "amount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "discountAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "freightAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "termsAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "tax": { "$ref": "#/definitions/tax" },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        }
      }
    },

    "unitMeasure": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "quantity": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999.999999
        }
      }
    }
  }
}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.stock.1.5.0-example-request.json
{ "reference": { "code": "PO-2159403-2",
                 "type": "buyer" },

  "buyer" : { "reference": { "code": "buyer-abc",
                             "type": "seller" }},

  "consumer" : { "reference": { "code": "consumer-xyz",
                                "type": "seller" },
                 "contract" : { "code": "contract-789",
                                "type": "seller" }},

  "shipTo" : { "location": { "mtn": "Jane Doe",
                             "rcp": "ECi Solutions, STG",
                             "alt": "Suite #200",
                             "dal": "4626 N 300 W",
                             "city": "Provo",
                             "region": "UT",
                             "postalCode": "84604"},
               "email": "shipping-contact@example.com",
               "phone": "1-555-555-5555"},

  "when" : "2018-04-24T17:00:00.000Z",

  "currency": { "code": "DKK",
                "name": "Danish krone",
                "number": 208,
                "precision": 2,
                "scale": 18},

  "itemsCount": 2,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller"},
              "quantity": 24,
              "location": { "name": "Main Warehouse",
                            "city": "Dallas",
                            "region": "TX" }}]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-package-number.json
{ "reference": { "referencesCount": 2,
                 "references": [ { "code": "PO-ABC123-2",
                                   "type": "buyer" }]},
  "package": "1 of 1",
  "itemsCount": 3,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" },
              "quantity": 24,
              "unitCost": 24.99 },
            { "reference": { "code": "def-456",
                             "type": "seller" },
              "quantity": 2,
              "unitCost": 2.99 },
            { "reference": { "code": "ghi-789",
                             "type": "seller" },
              "quantity": 1,
              "unitCost": 1.99 }]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.order.1.5.0-example-request.json
{ "reference": { "referencesCount": 2,
                 "references": [ {"code": "PO-2159403-2",
                                  "type": "buyer" },
                                 {"code": "PO-abc-q",
                                  "type": "consumer" }]},

  "buyer": { "reference": { "code": "buyer-abc",
                             "type": "seller" }},

  "consumer": { "reference": { "code": "consumer-xyz",
                                "type": "seller" },
                 "contract": { "code": "contract-789",
                                "type": "seller" }},

  "shipTo": { "location": { "mtn": "Jane Doe",
                             "rcp": "ECI Solutions, STG",
                             "alt": "Suite #200",
                             "dal": "4626 N 300 W",
                             "city": "Provo",
                             "region": "UT",
                             "postalCode": "84604"},
               "email": "shipping-contact@example.com",
               "phone": "1-555-555-5555"},

  "shippingMethod": { "code": "shipper-123",
                       "name": "usps-2day" },

  "when": "2018-04-24T17:00:00.000Z",

  "currency": { "code": "DKK",
                "name": "Danish krone",
                "number": 208,
                "precision": 18,
                "scale": 2},

  "itemsCount": 1,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller"},
              "quantity": 24 }]}
