=== EciStg/order-placement/rsrc-schema/src/vnd.eci.stg.receipt.1.5.0.json
{
  "id": "./vnd.eci.stg.receipt.1.5.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "receipt",
  "description": "",
  "type": "object",
  "additionalProperties": false,
  "properties": {

    "reference": { "$ref": "#/definitions/reference" },

    "code": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "name": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "description": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },

    "remarks": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },

    "when": {
      "description": "",
      "type": "string",
      "format": "date-time"
    },

    "whenExpected": {
      "description": "",
      "type": "string",
      "format": "date-time"
    },

    "billTo": { "$ref": "#/definitions/billTo" },

    "buyer": { "$ref": "#/definitions/buyer" },

    "consumer": { "$ref": "#/definitions/consumer" },

    "seller": { "$ref": "#/definitions/seller" },

    "shipTo": { "$ref": "#/definitions/shipTo" },

    "shippingMethod": { "$ref": "#/definitions/shippingMethod" },

    "location": { "$ref": "#/definitions/address" },

    "make": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "model": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "serialNumber": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "quantity": {
      "description": "",
      "type": "number",
      "minimum": 0,
      "maximum": 999999999.999999
    },

    "unitMeasure": { "$ref": "#/definitions/unitMeasure" },

    "unitCost": {
      "description": "",
      "type": "number",
      "minimum": 0,
      "maximum": 999999999999.999999
    },

    "total": { "$ref": "#/definitions/total"},

    "currency": { "$ref": "#/definitions/currency"},

    "package": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "shipment": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "tracking": {
      "description": "",
      "type": "string",
      "minLength": 1,
      "maxLength": 32
    },

    "itemsCount": {
      "description": "number of things in the items collection",
      "type": "number",
      "minimum": 1,
      "maximum": 1000
    },

    "items": {
      "description": "",
      "type": "array",
      "minItems": 1,
      "maxItems": 1000,
      "items": {
        "$ref": "#"
      }
    }
  },

  "definitions": {

    "address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "msc": {
          "description": "mail stop code",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "mtn": {
          "description": "attention line",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "rcp": {
          "description": "recipient or business name",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "alt": {
          "description": "alternate location",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "dal": {
          "description": "delivery address line",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "city": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "region": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "postalCode": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        },

        "country": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        }
      }
    },

    "billTo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "buyer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "consumer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" },

        "contract": { "$ref": "#/definitions/reference" }
      }
    },

    "contact": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        }
      }
    },

    "currency": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "number": {
          "description": "",
          "type": "number",
          "minimum": 1,
          "maximum": 999
        },

        "precision": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 18
        },

        "scale": {
          "description": "",
          "type": "number",
          "minimum": 1,
          "maximum": 6
        }
      }
    },

    "reference": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "type": { "$ref": "#/definitions/reference/definitions/referenceTypeEnum" },

        "referencesCount": {
          "description": "number of things in the references collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "references": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/reference"
          }
        }
      },

      "definitions": {
        "referenceTypeEnum": {
          "type": "string",
          "enum": ["buyer", "consumer", "manufacturer", "seller" ]
        }
      }
    },

    "seller": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "taxID": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" }
      }
    },

    "shippingMethod": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "billTo": { "$ref": "#/definitions/billTo" },

        "itemsCount": {
          "description": "number of shipping methods in the collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "items": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "items": {
            "$ref": "#/definitions/shippingMethod"
          }
        }
      }
    },

    "shipTo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "reference": { "$ref": "#/definitions/reference" },

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "location": { "$ref": "#/definitions/address" },

        "email": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "phone": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "contact": { "$ref": "#/definitions/contact" },

        "isDropShip": {
          "description": "",
          "type": "boolean"
        }
      }
    },

    "tax": {
      "type": "object",
      "properties": {

        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "amount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "authority": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "itemsCount": {
          "description": "number of things in the items collection",
          "type": "number",
          "minimum": 1,
          "maximum": 1000
        },

        "items": {
          "description": "",
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/tax"
          }
        }
      },

      "additionalProperties": false
    },

    "total": {
      "type": "object",
      "additionalProperties": false,
      "properties": {

        "amount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "discountAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "freightAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "termsAmount": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999999.999999
        },

        "tax": { "$ref": "#/definitions/tax" },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        }
      }
    },

    "unitMeasure": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "name": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 32
        },

        "description": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },

        "remarks": {
          "description": "",
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },

        "quantity": {
          "description": "",
          "type": "number",
          "minimum": 0,
          "maximum": 999999999.999999
        }
      }
    }
  }
}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-many-shipments-one-document.json
{ "reference": { "referencesCount": 2,
                 "references": [ { "code": "PO-ABC123-2",
                                   "type": "buyer" },
                                 { "code": "PO-XYZ-a",
                                   "type": "consumer" }]},

  "buyer": { "reference": { "code": "buyer-abc",
                            "type": "seller" }},

  "shipTo": { "location": { "mtn": "Jane Doe",
                            "rcp": "ECI Solutions, STG",
                            "alt": "Suite #200",
                            "dal": "4626 N 300 W",
                            "city": "Provo",
                            "region": "UT",
                            "postalCode": "84604" },
              "email": "shipping-contact@example.com",
              "phone": "1-555-555-5555" },

  "itemsCount": 3,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" },
              "quantity": 24,
              "unitCost": 24.99,
              "tracking": "T-123-ABC" },
            { "reference": { "code": "def-456",
                             "type": "seller" },
              "quantity": 2,
              "unitCost": 2.99,
              "tracking": "T-123-ABC" },
            { "reference": { "code": "ghi-789",
                             "type": "seller" },
              "quantity": 1,
              "unitCost": 1.99,
              "tracking": "T-456-DEF" }]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.stock.1.5.0-known-consumer-by-address-request.json
{ "buyer": { "reference": { "code": "buyer-abc",
                            "type": "seller" }},

  "consumer": { "location": { "rcp": "My Customer",
                              "dal": "10491 Old State Rd.",
                              "city": "Captiol City",
                              "region": "Alaska",
                              "postalCode": "99999-44444"},
                "phone": "916-363-2666"},
  "itemsCount": 1,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" }}]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-one-order-many-shipments-many-receipts.json-1.json
{ "reference": { "referencesCount": 2,
                 "references": [{ "code": "PO-ABC123-2",
                                  "type": "buyer" },
                                { "code": "PO-XYZ-a",
                                  "type": "consumer" }]},

  "shippingMethod": { "code": "shipper-123",
                      "name": "usps 2day" },

  "when": "2018-04-24T17:00:00.000Z",
  "whenExpected": "2018-04-26T17:11:30.000Z",
  "tracking": "T-123-ABC",

  "itemsCount": 2,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller"},
              "quantity": 24,
              "unitCost": 24.99 },
            { "reference": { "code": "def-456",
                             "type": "seller" },
              "quantity": 2,
              "unitCost": 2.99 },
            { "reference": { "code": "ghi-789",
                             "type": "seller" }}]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.stock.1.5.0-known-consumer-contract-request.json
{ "buyer" : { "reference": { "code": "buyer-abc",
                             "type": "seller" }},
  "consumer" : { "reference": { "code": "consumer-xyz",
                                "type": "seller" },
                 "contract" : { "code": "contract-789",
                                "type": "seller" }},
  "itemsCount": 1,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" }}]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-single-order-single-receipt-no-items.json
{ "reference": { "referencesCount": 2,
                 "references": [{ "code": "PO-ABC123-2",
                                  "type": "buyer" },
                                { "code": "PO-XYZ-a",
                                  "type": "consumer" }]},

  "when": "2018-04-24T17:00:00.000Z",
  "whenExpected": "2018-04-26T17:11:30.000Z",
  "tracking": "T-123-ABC" }

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.stock.1.5.0-known-consumer-request.json
{ "buyer" : { "reference": { "code": "buyer-abc",
                             "type": "seller" }},
  "consumer" : { "reference": { "code": "consumer-xyz",
                                "type": "seller" }},
  "itemsCount": 1,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" }}]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-one-order-many-shipments-one-receipt.json
{ "reference": { "referencesCount": 2,
                 "references": [ { "code": "PO-ABC123-2",
                                   "type": "buyer" },
                                 { "code": "PO-XYZ-a",
                                   "type": "consumer" }]},

  "buyer": { "reference": { "code": "buyer-abc",
                            "type": "seller" }},

  "shipTo": { "location": { "mtn": "Jane Doe",
                            "rcp": "ECI Solutions, STG",
                            "alt": "Suite #200",
                            "dal": "4626 N 300 W",
                            "city": "Provo",
                            "region": "UT",
                            "postalCode": "84604" },
              "email": "shipping-contact@example.com",
              "phone": "1-555-555-5555" },

  "itemsCount": 3,
  "items": [{ "reference": { "code": "abc-123",
                             "type": "seller" },
              "quantity": 24,
              "unitCost": 24.99,
              "shippingMethod": { "code": "shipper-123",
                                  "name": "usps 2day" },
              "when": "2018-04-24T17:00:00.000Z",
              "whenExpected": "2018-04-26T17:11:30.000Z",
              "tracking": "T-123-ABC" },
            { "reference": { "code": "def-456",
                             "type": "seller" },
              "quantity": 2,
              "unitCost": 2.99,
              "shippingMethod": { "code": "shipper-123",
                                  "name": "usps 2day" },
              "when": "2018-04-24T17:00:00.000Z",
              "whenExpected": "2018-04-26T17:11:30.000Z",
              "tracking": "T-123-ABC" },
            { "reference": { "code": "ghi-789",
                             "type": "seller" },
              "quantity": 1,
              "unitCost": 1.99,
              "shippingMethod": { "code": "shipper-ABC",
                                  "name": "fedx 2day" },
              "when": "2018-04-24T17:00:00.000Z",
              "whenExpected": "2018-04-26T17:11:30.000Z",
              "tracking": "T-456-DEF" }]}

=== EciStg/order-placement/rsrc-schema/tst/vnd.eci.stg.receipt.1.5.0-one-order-many-shipments-many-receipts.json-2.json
{ "reference": { "referencesCount": 2,
                 "references": [ { "code": "PO-ABC123-2",
                                   "type": "buyer" },
                                 { "code": "PO-XYZ-a",
                                   "type": "consumer" }]},
  "tracking": "T-456-DEF",
  "itemsCount": 1,
  "items": [
    { "reference": { "code": "ghi-789",
                     "type": "seller" },
      "quantity": 1,
      "unitCost": 1.99 }]}
